---
title: "7. Geminates"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)

df <- read_tsv("data/speakers.csv")

results <- read_tsv("data/results.tsv")
correspondence <- read_tsv("data/correspondence.tsv")

results %>% 
  left_join(correspondence) %>% 
  left_join(df) %>% 
  filter(!grepl("[tʃrlnm]", folVowel),
       !grepl("[tʃrlnm]", prevVowel)) %>% 
  mutate(repetition = ifelse(repetition == "--undefined--", "", repetition),
         repetition = paste(context, repetition),
         folVowDur = as.double(ifelse(folVowDur == "--undefined--",NA, folVowDur)),
         geminate = ifelse(grepl("[ː:]", stop),"+g", "-g"),
         aff_type = ifelse(grepl("[sz]", stop),"dent", NA),
         aff_type = ifelse(grepl("[ʃʒšžǯ]", stop),"alv", aff_type),
         aff_type = ifelse(grepl("ɬ", stop),"lat", aff_type),
         aff_type = ifelse(grepl("χ", stop),"uv", aff_type),
         affric = ifelse(grepl("ɬ", stop),"affricate", affric),
         affric = ifelse(grepl("χ", stop),"affricate", affric),
         affric = ifelse(poa == "uvular", "plain", affric),
         aff_type = ifelse(grepl("χ", stop),"uv", aff_type),
         poa = ifelse(stop == "ɡ", "velar", poa),
         aff_type = factor(aff_type, levels = c("dent", "alv", "lat", "uv")),
         affric = factor(affric, levels = c("plain", "affricate")),
         voice = ifelse(str_detect(stop, "[bdgɡɢ]"), "+v", "-v")) %>%  
  mutate(fric = fric * 1000,
         postfric = postfric*1000,
         folVowDur = folVowDur*1000,
         closdur = closdur*1000,
         VOT = fric + postfric,
         cd_n = closdur/folVowDur,
         vot_n = VOT/folVowDur,
         utterance = paste0(context, "_", repetition),
         poa = factor(poa, levels = c("bilabial", "dental", "velar", "uvular")),
         c_type = ifelse(glott == "glottalic", "ej", voice),
         c_type = ifelse(geminate == "+g", paste0(c_type, ",", "+g"), c_type),
         c_type = factor(c_type, levels = c("+v", "-v", "ej", "-v,+g", "ej,+g"))) ->
  final_df

final_df %>%
  mutate(prevVowel = ifelse(is.na(prevVowel), "#", prevVowel)) %>% 
  filter(
    repetition != "iso 4",
    repetition != "iso 5",
    repetition != "iso 6",
    repetition != "iso 0",
    repetition != "iso i",
    repetition != "iso NA",
    prevVowel != "b",
    prevVowel != "g",
    prevVowel != "g\\)",
    prevVowel != "j\\)",
    prevVowel != "k",
    prevVowel != "\\(k",
    prevVowel != "k:",
    prevVowel != "k'",
    prevVowel != "\\(qχ",
    prevVowel != "s",
    prevVowel != "\\(s",
    prevVowel != "w",
    prevVowel != "z",
    prevVowel != "χ",
    folVowel != "ʔ",
    folVowel != "ɢ",
    folVowel != "ʔ\\)",
    folVowel != "b",
    folVowel != "j",
    folVowel != "j",
    folVowel != "j)",
    folVowel != "\\(j\\)",
    folVowel != "k'",
    folVowel != "p'",
    folVowel != "q",
    folVowel != "qχ",
    folVowel != "w",
    folVowel != "\\(w",
    folVowel != "w\\)",
    folVowel != "\\(w\\)",
    stop != "(ʔ",
    stop != "(ʔ)",
    stop != "ʔ)",
    stop != "n:)",
    stop != "n)",
    stop != "(n",    
    stop != "(h",
    stop != "(j",
    stop != "(j)",
    stop != "j)",
    stop != "(s",
    stop != "(w)") ->
  final_df

final_df %>% 
  mutate(stop_label = str_replace_all(final_df$stop, "[wʲʷˤχ\\(\\)\\?]", ""),
         folVowel = str_replace_all(final_df$folVowel, "[\\(\\)]", "")) ->
  final_df
```

## Selected words
```{r}
final_df %>%
  filter(word == "ɢaˤraˤɢaˤl"|
           word == "gʲaɢara"|
           word == "mɨtʃ'aqaji"|
           word == "mɨtʃ'aqai"|
           word == "mɨtʃ'aqa"|
           word == "katʃalaj"|
           word == "katʃaldɨ"|
           word == "katʃal"|
           word == "ɢatʃaχ"|
           word == "ɢatʃaχar") %>% 
  filter(position == "medial") %>% 
  mutate(word = str_replace_all(word, "ɢatʃaχar", "ɢatʃaχ"),
         word = str_replace_all(word, "katʃalaj", "katʃal"),
         word = str_replace_all(word, "katʃaldɨ", "katʃal"),
         word = str_replace_all(word, "mɨtʃ'aqaji", "mɨtʃ'aqa"),
         word = str_replace_all(word, "mɨtʃ'aqai", "mɨtʃ'aqa")) ->
  gem
```

## Absolute values
### CD
```{r}
gem %>% 
  ggplot(aes(word, closdur, fill = filename))+
  geom_boxplot()+
  #geom_point()+  
  theme_bw()+
  labs(y = "CD (ms)", x = "")+
  coord_flip()
```

### VOT
```{r}
gem %>% 
  ggplot(aes(word, VOT, fill = filename))+
  geom_boxplot()+
  theme_bw()+
  labs(y = "VOT (ms)", x = "")+
  coord_flip()
```
## Relative values
### CD
```{r}
gem %>% 
  mutate(rel_cd = closdur/totdur) %>% 
  ggplot(aes(word, rel_cd, fill = filename))+
  geom_boxplot()+
  theme_bw()+
  labs(y = "CD (ms)", x = "")+
  coord_flip()
```

### VOT
```{r}
gem %>% 
  mutate(rel_vot = VOT/totdur) %>% 
  ggplot(aes(word, rel_vot, fill = filename))+
  geom_boxplot()+
  theme_bw()+
  labs(y = "CD (ms)", x = "")+
  coord_flip()
```

